### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by YomaDan** [wcandillon/react-progressive-image-loading#31]
(node:6860) UnhandledPromiseRejectionWarning: ReferenceError: Image is not defined

**Comment by wcandillon** [comment]
How do you get such error? Is it possible that you are running it into react native instead of React JS? If you are looking for the RN equivalent of this component, you need to use https://github.com/wcandillon/react-native-expo-image-cache

Feel free to reopen if needed.

**Comment by YomaDan** [comment]
React desktop, nodejs

чт, 12 апр 2018 г., 16:07 William Candillon <notifications@github.com>:

**Comment by wcandillon** [comment]
Is it possible that `Image` class is not available in this environment but only in the web?

**Comment by YomaDan** [comment]
Only web, only client side ofter server side react rendering

чт, 12 апр 2018 г., 16:10 William Candillon <notifications@github.com>:

**Comment by LeTanque** [comment]
I'm getting a similar error on React desktop using next.js ssr.
